/**
 * 從正本生成可搜尋的文档索引 —— **不複製規格，只匯總入口**。
 *
 * 正本仍在：
 *   GAP-*  → `.claude/agents/*.md` §4
 *   gate   → `scripts/gate-*.ts` 檔頭
 *
 * 產出：
 *   docs/generated/gap-index.md
 *   docs/generated/gate-index.md
 *
 * 用法：pnpm gen:doc-index
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = join(ROOT, 'docs/generated');
const HEADER =
  '<!-- AUTO-GENERATED by scripts/gen-doc-index.ts — do not edit. Run: pnpm gen:doc-index -->\n\n';

type GapRow = { id: string; agent: string; trap: string; source: string };

function parseAgentGaps(agent: string, text: string): GapRow[] {
  const block = text.match(/## 4 ·[^\n]*\n\n([\s\S]*?)(?=\n## |$)/)?.[1];
  if (!block) return [];
  const rows: GapRow[] = [];
  for (const line of block.split('\n')) {
    if (!line.startsWith('|') || line.includes('---') || line.includes('Trap |')) continue;
    const cols = line
      .split('|')
      .map((c) => c.trim())
      .filter(Boolean);
    if (cols.length < 2) continue;
    const trap = cols[0];
    const source = cols[1];
    if (trap === undefined || source === undefined) continue;
    for (const id of source.match(/GAP-\d+/g) ?? []) {
      rows.push({ id, agent, trap, source });
    }
  }
  return rows;
}

export function buildGapIndex(): string {
  const dir = join(ROOT, '.claude/agents');
  const rows = readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .flatMap((file) =>
      parseAgentGaps(file.replace(/\.md$/, ''), readFileSync(join(dir, file), 'utf8')),
    );
  rows.sort((a, b) => Number(a.id.slice(4)) - Number(b.id.slice(4)));
  const body = rows.map((r) => `| ${r.id} | ${r.agent} | ${r.trap} | ${r.source} |`).join('\n');
  return `${HEADER}# GAP index（generated）

> 正本：\`.claude/agents/<agent>.md\` §4。本檔只供搜尋；**以 agent 檔為準**。

| ID | Agent | Trap | Source |
|---|---|---|---|
${body}
`;
}

export function gateSummary(src: string): string {
  const block = src.match(/\/\*\*([\s\S]*?)\*\//)?.[1] ?? '';
  const line = block
    .split('\n')
    .map((l) => l.replace(/^\s*\*\s?/, '').trim())
    .find((l) => l.startsWith('這支在守什麼：'));
  if (!line) return '（無檔頭摘要）';
  return line.replace(/^這支在守什麼：/, '').trim();
}

export function buildGateIndex(): string {
  const dir = join(ROOT, 'scripts');
  const rows = readdirSync(dir)
    .filter((f) => f.startsWith('gate-') && f.endsWith('.ts'))
    .sort()
    .map((f) => {
      const src = readFileSync(join(dir, f), 'utf8');
      return `| \`${f}\` | ${gateSummary(src)} |`;
    });
  return `${HEADER}# Gate index（generated）

> 正本：\`scripts/gate-*.ts\` 檔頭。本檔只供瀏覽；**以 gate 原始檔為準**。

| Gate | 在守什麼 |
|---|---|
${rows.join('\n')}
`;
}

export function generatedFiles(): Record<string, string> {
  return {
    'docs/generated/gap-index.md': buildGapIndex(),
    'docs/generated/gate-index.md': buildGateIndex(),
  };
}

export function writeGenerated(): void {
  mkdirSync(OUT, { recursive: true });
  for (const [rel, content] of Object.entries(generatedFiles())) {
    writeFileSync(join(ROOT, rel), content, 'utf8');
  }
}

if (process.argv[1]?.endsWith('gen-doc-index.ts')) {
  writeGenerated();
  console.log('gen-doc-index: wrote docs/generated/gap-index.md, gate-index.md');
}
